### ISSUE TITLE
Version recognition

### ISSUE THREAD

**Issue by dustinthomas** [BBN-Q/Instruments.jl#11]
I am using Julia 1.0.0 per the docs however I get this error when trying to install the package.

ERROR: Unsatisfiable requirements detected for package Instruments [98003276]:
 Instruments [98003276] log:
 ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

its seems in the project.tmol you call the version 0.1.0 however Julia's convention is 1.0.0. Not sure if this is issue but it seems to be.

**Comment by catosp** [comment]
Try:
add Instruments#master
This solution was proposed by matthewware and work on me.

**Comment by matthewware** [comment]
The right solution would be to cut a new release and update the package registry.  I'll try to get to this later in the week.  Let me know if moving to the master branch doesn't fix things for you.

**Comment by iuliancioarca** [comment]
I found this package very useful and it would be a pitty to let it undiscovered by other other people because it was removed from the official package registry. Is it still maintained? How can I help to update it to be added again to the registry? Thank you for the great work!

**Comment by gribeill** [comment]
Thanks for the kind words! Unfortunately this package isn't really under active development right now; we are happy to accept pull requests though so if there are specific features you'd like to add please feel free to do so.

**Comment by matthewware** [comment]
With the redesign of the TagBot/Registry, I think this issue is obsolete.  At the moment, I'm trying to reregister the package.  Until then, anyone with issues can always install directly:
```
pkg> add https://github.com/BBN-Q/Instruments.jl
```
