### ISSUE TITLE
Installation via registry not possible anymore

### ISSUE THREAD

**Issue by casabre** [BBN-Q/Instruments.jl#15]
The installation with `Pkg.add("Instruments")` is not working because the package is not listed in the registry anymore.

As a workaround, one has to install it with
```Julia
pkg> add https://github.com/BBN-Q/Instruments.jl
```

**Comment by matthewware** [comment]
I'd been waiting from some time for the package to get merged into the registry.  Let me see if I can resubmit.

**Comment by matthewware** [comment]
https://github.com/JuliaRegistries/General/pull/14210

We'll see if we have better luck this time.

**Comment by casabre** [comment]
@matthewware I wasn't aware of that. Thanks for resubmitting and currently, the direct URL adding works for me too. It was just confusing in the beginning. Thanks a lot.

**Comment by matthewware** [comment]
I believe the package is registered again and you should be able to install directly through the package manager.  Let me know if you still have issues.

**Comment by casabre** [comment]
It is working now! Thanks for resubmitting. Is the R&S supplementation included in that version .0.2.0?

**Comment by matthewware** [comment]
Yes, It should pull from the R&S commit.
